[build]
  command = "npm run build"
  publish = "build/static"
  functions = "build/server.js"

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200