[build]
  command = "npm run build"
  publish = "public"
  functions = "src/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/new"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''