[build]
  command = "npm run build"
  publish = "public"
  functions = "src/functions"

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200